
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: on-failure
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      net_con:

  pg_db:
    container_name: pg_db
    image: postgres:16
    environment:
      - POSTGRES_USER=${PG_ADMIN}
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ADMIN}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./secrets/dumps:/docker-entrypoint-initdb.d
    # внешний | внутренний
    ports:
      - "127.0.0.1:5431:5432"
    networks:
      net_con:

  web_app:
    build: .
    container_name: web_app
    restart: on-failure
    environment:
      - ENV_FILE=/run/secrets/.env
      - PRIVATE_KEY_PATH=/run/secrets/private_key.pem
      - PUBLIC_KEY_PATH=/run/secrets/public_key.pem
    depends_on:
      pg_db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/public/healthcheck')\""]
      interval: 30s
      timeout: 5s
      retries: 3
    secrets:
      - .env
      - private_key.pem
      - public_key.pem
    ports:
      - "127.0.0.1:8100:8000"
    networks:
      net_con:



volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

secrets:
  .env:
    file: .env
  private_key.pem:
    file: ./secrets/keys/private_jwt.pem
  public_key.pem:
    file: ./secrets/keys/public_jwt.pem

networks:
  net_con:
    driver: bridge